title: "Oliver Barclay"
description: "My personal github site"
author: "Oliver Barclay"
include:
  - assets/html
  - assets/js
  - assets/css  # Add this line
baseurl: ""
url: "https://username.github.io"